# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65ef73dcf599588e1838c2609b60f30351161087709e8639a55e707eaa37c162b7cc9a9852f6e9b054c412de6009b8f00e287affbf51a98c71e7baf484c2ac96

test:
  secret_key_base: e54406c372c568e9dc38a0b454b2c1556fe535ad5ffc30554b5e0f9b3956a2fe91ad3d334e98341ac7fc3cd4c96886c750fc73950f06881125460c55e1ceed0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
